name: Sideways
favicon: null
layout_spectrum: 0.2288949443027377
typography_spectrum: 0.4832932536955923
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2516956008039415
  lightness: 0.3342031720094383
  saturation: 0.8702018402982503
  rhythmicContrast: 0.13865697290748358
purpose: []
